[build]
publish = "exampleSite/public" 
command = "cd exampleSite && hugo --gc --themesDir ../.. --config config-prod.toml"

[context.production.environment]
HUGO_VERSION = "0.62.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
